[2025-06-03T06:46:39.899+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: prepare_churn_dataset.extract scheduled__2025-06-03T00:00:00+00:00 [queued]>
[2025-06-03T06:46:39.910+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: prepare_churn_dataset.extract scheduled__2025-06-03T00:00:00+00:00 [queued]>
[2025-06-03T06:46:39.911+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-06-03T06:46:39.929+0000] {taskinstance.py:1382} INFO - Executing <Task(_PythonDecoratedOperator): extract> on 2025-06-03 00:00:00+00:00
[2025-06-03T06:46:39.935+0000] {standard_task_runner.py:57} INFO - Started process 137 to run task
[2025-06-03T06:46:39.943+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'prepare_churn_dataset', 'extract', 'scheduled__2025-06-03T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/churn.py', '--cfg-path', '/tmp/tmp2vt44fkb']
[2025-06-03T06:46:39.944+0000] {standard_task_runner.py:85} INFO - Job 8: Subtask extract
[2025-06-03T06:46:40.014+0000] {task_command.py:416} INFO - Running <TaskInstance: prepare_churn_dataset.extract scheduled__2025-06-03T00:00:00+00:00 [running]> on host 2ad5921a312f
[2025-06-03T06:46:40.132+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='prepare_churn_dataset' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2025-06-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-03T00:00:00+00:00'
[2025-06-03T06:46:40.150+0000] {base.py:73} INFO - Using connection ID 'source_db' for task execution.
[2025-06-03T06:46:40.176+0000] {warnings.py:109} WARNING - /opt/***/dags/churn.py:73: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data = pd.read_sql(sql, conn)

[2025-06-03T06:46:40.282+0000] {python.py:194} INFO - Done. Returned value was:      customer_id  begin_date  ... dependents multiple_lines
0     7590-VHVEG  2020-01-01  ...         No           None
1     5575-GNVDE  2017-04-01  ...         No             No
2     3668-QPYBK  2019-10-01  ...         No             No
3     7795-CFOCW  2016-05-01  ...         No           None
4     9237-HQITU  2019-09-01  ...         No             No
...          ...         ...  ...        ...            ...
7038  6840-RESVB  2018-02-01  ...        Yes            Yes
7039  2234-XADUH  2014-02-01  ...        Yes            Yes
7040  4801-JZAZL  2019-03-01  ...        Yes           None
7041  8361-LTMKD  2019-07-01  ...         No            Yes
7042  3186-AJIEK  2014-08-01  ...         No             No

[7043 rows x 20 columns]
[2025-06-03T06:46:40.470+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py:373: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if _pandas_api.is_sparse(col):

[2025-06-03T06:46:40.598+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=prepare_churn_dataset, task_id=extract, execution_date=20250603T000000, start_date=20250603T064639, end_date=20250603T064640
[2025-06-03T06:46:40.673+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-06-03T06:46:40.699+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
