[2025-06-03T06:57:49.816+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: prepare_churn_dataset.create_table scheduled__2025-06-03T00:00:00+00:00 [queued]>
[2025-06-03T06:57:49.824+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: prepare_churn_dataset.create_table scheduled__2025-06-03T00:00:00+00:00 [queued]>
[2025-06-03T06:57:49.824+0000] {taskinstance.py:1361} INFO - Starting attempt 3 of 3
[2025-06-03T06:57:49.837+0000] {taskinstance.py:1382} INFO - Executing <Task(_PythonDecoratedOperator): create_table> on 2025-06-03 00:00:00+00:00
[2025-06-03T06:57:49.844+0000] {standard_task_runner.py:57} INFO - Started process 307 to run task
[2025-06-03T06:57:49.848+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'prepare_churn_dataset', 'create_table', 'scheduled__2025-06-03T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/churn.py', '--cfg-path', '/tmp/tmpw0t_9tmr']
[2025-06-03T06:57:49.849+0000] {standard_task_runner.py:85} INFO - Job 13: Subtask create_table
[2025-06-03T06:57:49.895+0000] {task_command.py:416} INFO - Running <TaskInstance: prepare_churn_dataset.create_table scheduled__2025-06-03T00:00:00+00:00 [running]> on host 2ad5921a312f
[2025-06-03T06:57:49.979+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='prepare_churn_dataset' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2025-06-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-03T00:00:00+00:00'
[2025-06-03T06:57:49.983+0000] {logging_mixin.py:154} INFO - hook:  <***.providers.postgres.hooks.postgres.PostgresHook object at 0x7f91ca60c370>
[2025-06-03T06:57:49.993+0000] {base.py:73} INFO - Using connection ID 'destination_db' for task execution.
[2025-06-03T06:57:49.995+0000] {logging_mixin.py:154} INFO - db_conn:  Engine(postgresql://mle_20250507_60d03b0a2f_freetrack:***@rc1b-uh7kdmcx67eomesf.mdb.yandexcloud.net:6432/playground_mle_20250507_60d03b0a2f?__extra__=%7B%7D)
[2025-06-03T06:57:49.997+0000] {logging_mixin.py:154} INFO - users_churn:  users_churn
[2025-06-03T06:57:49.998+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/sql/base.py", line 1223, in __getattr__
    return self._index[key]
KeyError: 'ustomer_id'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/churn.py", line 57, in create_table
    print('users_churn: ', users_churn.c.ustomer_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/sql/base.py", line 1225, in __getattr__
    util.raise_(AttributeError(key), replace_context=err)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
AttributeError: ustomer_id
[2025-06-03T06:57:50.007+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=prepare_churn_dataset, task_id=create_table, execution_date=20250603T000000, start_date=20250603T065749, end_date=20250603T065750
[2025-06-03T06:57:50.022+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 13 for task create_table (ustomer_id; 307)
[2025-06-03T06:57:50.060+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-06-03T06:57:50.076+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
